name: rcs_scouting
description: A new Flutter project.
publish_to: 'none'
version: 0.2.9

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter
  provider: ^6.0.5
  yaml: ^3.1.1
  vector_math: any
  http: ^0.13.5
  shared_preferences: ^2.0.18
  uuid: ^3.0.7
  quantity_input: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: OrionPax
    fonts:
    - asset: fonts/OrionPax.ttf
    - asset: fonts/OrionPaxItalic.ttf
      style: italic
  - family: BraveEightyOne
    fonts:
     - asset: fonts/BraveEightyOneRegular.ttf
  assets:
    - assets/
    
